[package]
name = "rust_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
nmea = { version = "0.6.0", default-features=false, features = ["GNSS"] }

[features]
default = [ ]

